"""added form name

Revision ID: 2c2c80066488
Revises: 
Create Date: 2025-07-23 09:58:29.810882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c2c80066488'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('published_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('published_form', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
